name: 刷步数

on:
  schedule:
    - cron: '3 8 * * *'    # 对应北京时间 16:03
    - cron: '7 9 * * *'    # 对应北京时间 17:07
    - cron: '9 10 * * *'   # 对应北京时间 18:09
  workflow_dispatch:

concurrency:
  group: repo-write-master
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout codes
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：README
          fetch-depth: 0

      - name: 初始化Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: 开始
        env:
          CONFIG: ${{ secrets.CONFIG }}
          AES_KEY: ${{ secrets.AES_KEY }}
          SENDKEY: ${{ secrets.SENDKEY }}
        run: |
          pip3 install requests pytz pycryptodome
          python3 main.py

      - name: 提交更新数据
        if: success()
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git pull --rebase --autostash origin master
          git add encrypted_tokens.data
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          current=$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')
          git commit -m "[${current}] update tokens"
          git push origin master
